### ISSUE TITLE
To Do List for Release #1.0.0

### ISSUE THREAD

**Issue by Sawa121212** [Sawa121212/AvaVKPlayer#9]
## Now
# Code
- [ ] Add Regions for Prism
- [x] Add Navigation for Prism #10
- [ ] Make automatic copy of DLL-libraries to the assembly
- [ ] Optimize data loading
- [ ] Add to Models method "Equals" @MukhinDmitriy 

# UI / Functional
- [x] Add localization #10
    - [ ] Update localization
- [x] Add the ability to change the theme of the application #10
- [x] Add "About" and "Settings" windows #10
- [x] Update "Player" control view #11 
- [x] Update "Albums" control view #12 
    - [ ] Update "Album" control view
- Add the ability to download:
    - [ ] all music at once
    - [ ] an album
- Add the ability to cache:
    - [ ] all music
    - [ ] albumы

## Future (Release # 2)
- [ ] View music of friends
- [ ] Go to Avalonia 11
